# Generated by Django 5.0.3 on 2024-03-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_subcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Maincategory',
            new_name='maincategory',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
