# Generated by Django 5.0.3 on 2024-04-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
